#!/bin/sh
#
# Special thanks to zipleen for the original Tomato/DD-WRT script that this 
# one is based on:
#
# https://github.com/zipleen/tomato-ddwrt-meo-iptv-scripts/blob/master/dhcpevent.sh
# 
# ----
#
# This script is run by the udhcpc program (via the wan-start script).
#
# The following variables are passed into it (w/example values):
#
# $interface: vlan12
# $vlan_ip: 10.x.x.x
# $subnet: 255.255.192.0
# $vlan_gateway: 10.y.y.y
#
# Its purpose is to set up the routes so that requests to MEO specific services
# from the private local network are routed to the MEO IPTV/VoIP vlan.

vlan_iface=$interface
vlan_ip=$ip
vlan_subnet=$subnet
vlan_gateway=$router

# duped from _net_config
vlan_ip_file="/tmp/vlan_ip"

#-----------------------------------------------------------------------------
# These routes are set up on the original hardware, as observed in a backup 
# file (user.ini).
#-----------------------------------------------------------------------------
configure_meo_routes () {
  logger "$0: setting up VLAN routes"
  
  # rule add chain=rt_user_labels index=1 dstip=10.173.[192-255].* log=disabled state=enabled label=toVideoNet
  ## 10.173.0.1 -> 10.173.255.254
  ## 10.173.0.0 / 255.255.255.0 / 16
  ## http://www.aboutmyip.com/AboutMyXApp/SubnetCalculator.jsp?ipAddress=10.173.0.0&cidr=16
  route add -net 10.173.0.0 netmask 255.255.0.0 gw $vlan_gateway dev $vlan_iface
  
  # rule add chain=rt_user_labels index=2 dstip=213.13.[16-24].* log=disabled state=enabled label=toVideoNet
  # 213.13.[16-24]
  ## 213.13.16.1 -> 213.13.31.254
  ## 213.13.16.0 / 255.255.240.0 / 20
  ## http://www.aboutmyip.com/AboutMyXApp/SubnetCalculator.jsp?ipAddress=213.13.16.0&cidr=20
  # Covers VoIP Proxy: proxy.ims.iptv.telecom.pt (213.13.24.225)
  route add -net 213.13.16.0 netmask 255.255.240.0 gw $vlan_gateway dev $vlan_iface 
  
  # rule add chain=rt_user_labels index=3 dstip=194.65.[46-47].* log=disabled state=enabled label=toVideoNet
  # 194.65.46.0 -> 194.65.47.254
  ## 194.65.46.0 / 255.255.254.0 / 23 
  ## http://www.aboutmyip.com/AboutMyXApp/SubnetCalculator.jsp?ipAddress=194.65.46.0&cidr=23 
  # Covers VLAN DNS servers: 194.65.47.44 and 194.65.47.43
  route add -net 194.65.46.0 netmask 255.255.254.0 gw $vlan_gateway dev $vlan_iface
                     
  logger "$0: saving vlan ip $vlan_ip to $vlan_ip_file"
  
  # Now that we have the routes set up, we need to set up some firweall rules:
  echo $vlan_ip > $vlan_ip_file
}

#-----------------------------------------------------------------------------
deconfig() {
  ifconfig $vlan_iface 0.0.0.0
}
 
#-----------------------------------------------------------------------------
bound() {

  # debug environment variables
  #env > /tmp/env
    
  logger "$0: bound event variables: ip: $vlan_ip, iface: $vlan_iface, router: $vlan_gateway"

  # define interface IP
  ifconfig $vlan_iface $vlan_ip netmask $vlan_subnet
  
  # rp_filter must be off on vlan12!!!
  echo 0 > /proc/sys/net/ipv4/conf/$vlan_iface/rp_filter
        
  configure_meo_routes
 
  logger "$0: completed"
}

#-----------------------------------------------------------------------------
renew() {
  # I'm lazy so I'm just goin to run all the commands again! Seems to work :P 
  bound
}
    
case $1 in
  deconfig)
    deconfig
  ;;
  bound)
    bound
  ;;
  renew)
    renew
  ;;
  update)
    renew
  ;;
esac
