#!/bin/sh

#---------------------------------------------------------------------------
update_tunlr_client () {
  logger "$0: (background) starting update of remote tunlr config with updated client IP"
  $CUSTOM_SCRIPT_DIR/tunlr-update-client 2>&1 &
  logger "$0: (background) update is on its way"
}

#---------------------------------------------------------------------------
# Update using dnsmadeeasy.com API
#---------------------------------------------------------------------------
update_dynamic_dns () {
  if [ -n "$WAN_IP_ADDRESS" ]; then
    logger "$0: using WAN IP address $WAN_IP_ADDRESS for dynamic DNS"
    resp=`wget -q -c -O - $DYNDNS_URL`
    rcode=$?
    logger "$0: ddns response: $resp; result code: $rcode"
    if [ $resp != "success" ] && [ $resp != "error-record-ip-same" ]; then
       return 1
    else
       return 0
    fi
  else
    logger "$0: WARNING: no WAN IP address available.  Not updating dynamic DNS."
    return 1
  fi
}

#---------------------------------------------------------------------------
# Based on: 
# https://github.com/zipleen/tomato-ddwrt-meo-iptv-scripts/blob/master/startiptv.sh
#---------------------------------------------------------------------------
start_igmp_proxy () {
  if [ `ps | grep 'igmpproxy' | grep $config_file | wc -l` -eq 0 ]; then
    logger "$0: starting igmp proxy"
    local_command 'igmpproxy' "igmpproxy -d -v $CUSTOM_CONFIG_DIR/meo-config-igmp"
    return $?
  else
    logger "$0: igmpproxy already running"
    return 0
  fi
}

#---------------------------------------------------------------------------
# Based on: 
# https://github.com/zipleen/tomato-ddwrt-meo-iptv-scripts/blob/master/startiptv.sh
#---------------------------------------------------------------------------
configure_vlan () {
  local script=$CUSTOM_SCRIPT_DIR/meo-post-dhcp-vlan-config 
  if [ -f "$script" ]; then
    logger "$0: kicking off vlan config"
    local_command 'udhcpc' "udhcpc -i $VLAN_IFACE -p /var/run/udhcpc0.pid -V $VLAN_VENDOR_CLASS -s $script"
    return $?
  else
    logger "$0: WARNING: script not found: $script"
    return 1
  fi
}

#===========================================================================

logger "$0 event called with args: $@"

source /jffs/scripts/custom/_net_functions
init_config

update_dynamic_dns && update_tunlr_client

# This technically doesn't depend on the WAN interface, but I'm not sure 
# there is a better hook for it than wan-start.
configure_vlan # && start_igmp_proxy

